name: Create a Git Tag for version in pyproject.toml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Insall Poetry
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry

      - name: Collect Package Version
        id: vars
        run: echo ::set-output name=pkg_version::$(poetry version -s)
        
      - name: Create a Git Tag
        uses: actions/github-script@v6
        env:
          PKG_VERSION: ${{ steps.vars.outputs.pkg_version }}
        with:
          script: |
            const { PKG_VERSION } = process.env
            
            resp = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${PKG_VERSION}`,
              sha: context.sha
            })
            
            console.log(resp)
